"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, ChefHat, ChevronDown, ChevronUp, Download, Flame, PackageOpen, Play, RefreshCw, ShieldCheck, Soup, Sparkles, Zap } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useCallback, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { KitchenSnapshot, KitchenStreamEvent, ScenarioId, StationId } from "@/lib/kitchen/types";

type MenuItem = "burger" | "fries" | "plantain" | "grilled-chicken" | "fried-chicken" | "jollof-rice" | "fried-rice" | "pasta" | "steak" | "fish" | "wings" | "salad" | "sandwich" | "yam-fries" | "vegetable-bowl";
const foods: { id: MenuItem; name: string; station: string }[] = [
  { id: "burger", name: "Smash Burger", station: "Prep + Grill" }, { id: "fries", name: "House Fries", station: "Fryer" }, { id: "plantain", name: "Fried Plantain", station: "Fryer" }, { id: "grilled-chicken", name: "Grilled Chicken", station: "Prep + Grill" }, { id: "fried-chicken", name: "Fried Chicken", station: "Prep + Fryer" }, { id: "jollof-rice", name: "Jollof Rice", station: "Pantry" }, { id: "fried-rice", name: "Fried Rice", station: "Pantry" }, { id: "pasta", name: "Creamy Pasta", station: "Pantry" }, { id: "steak", name: "Grilled Steak", station: "Prep + Grill" }, { id: "fish", name: "Grilled Fish", station: "Prep + Grill" }, { id: "wings", name: "Crispy Wings", station: "Prep + Fryer" }, { id: "salad", name: "Chopped Salad", station: "Pantry" }, { id: "sandwich", name: "Club Sandwich", station: "Prep + Pantry" }, { id: "yam-fries", name: "Yam Fries", station: "Fryer" }, { id: "vegetable-bowl", name: "Vegetable Bowl", station: "Prep + Pantry" },
];
const scenarios: { id: ScenarioId; title: string; copy: string }[] = [
  { id: "rush", title: "Normal dinner rush", copy: "Let the live agents handle the order without a crisis." }, { id: "fryer", title: "Fryer fails mid-service", copy: "The fryer goes offline after the agents have already started." }, { id: "allergy", title: "Late allergy note", copy: "A sesame allergy arrives while the food is being prepared." }, { id: "full", title: "Full pressure test", copy: "Fryer failure and allergy update hit the same live service." },
];
const stationInfo: Record<StationId, { title: string; copy: string; Icon: typeof ChefHat }> = {
  prep: { title: "Prep", copy: "Cleans, chops, seasons, breads food and handles allergy-safe prep.", Icon: ChefHat }, grill: { title: "Grill", copy: "Cooks burgers, chicken, steak and fish on the hot line.", Icon: Flame }, fryer: { title: "Fryer", copy: "Handles fries, plantain, fried chicken, wings and yam while watching fryer health.", Icon: Soup }, pantry: { title: "Pantry", copy: "Builds rice, pasta, salads, sandwiches and cold sides while checking stock.", Icon: PackageOpen }, expo: { title: "Expo", copy: "Watches the whole kitchen and is the final safety gate before a table is served.", Icon: ShieldCheck },
};

function Shell({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-[#f7fbff] text-[#0b1726]"><header className="sticky top-0 z-50 border-b border-black/5 bg-[#f7fbff]/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 sm:px-8"><Link href="/" className="flex items-center gap-2.5 font-semibold"><span className="grid size-9 place-items-center rounded-full bg-[#0b1726] text-white"><Zap className="size-4" fill="currentColor" /></span>Dinner Rush</Link><span className="rounded-full border border-[#b7dfff] bg-white px-3 py-1.5 text-[10px] font-medium text-[#1268a8]">Live Mozaik kitchen</span></div></header>{children}</main>; }

function Decisions({ snapshot }: { snapshot: KitchenSnapshot }) { return <section className="rounded-[28px] border border-black/5 bg-white p-5 shadow-[0_20px_60px_rgba(15,88,145,.07)]"><div className="flex items-end justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-[#2e89c8]">Live decision feed</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">What the agents are deciding right now</h2></div><span className="rounded-full bg-[#eaf7ff] px-3 py-2 text-xs text-[#1268a8]">{snapshot.loops.filter(x => !x.finishedAt).length} active</span></div><div className="mt-5 grid gap-2 md:grid-cols-2 xl:grid-cols-3"><AnimatePresence initial={false}>{snapshot.activities.slice(0,9).map(a => <motion.div key={a.id} initial={{opacity:0,y:-6}} animate={{opacity:1,y:0}} className={cn("rounded-2xl border p-3",a.tone==="danger"?"border-[#ffc7bd] bg-[#fff3f0]":"border-black/5 bg-[#f8fbfd]")}><p className="text-[10px] font-semibold text-[#2e89c8]">{a.actor}</p><p className="mt-1 text-xs leading-5 text-[#405166]">{a.message}</p></motion.div>)}</AnimatePresence></div></section>; }

function Workers({ snapshot }: { snapshot: KitchenSnapshot }) { return <section><div className="mb-4"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-[#2e89c8]">Kitchen floor</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">All five workers share the same live state.</h2></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{snapshot.stations.map(s => { const info=stationInfo[s.id]; const active=s.status==="thinking"||s.status==="working"; return <motion.article layout key={s.id} className={cn("relative min-h-72 overflow-hidden rounded-[26px] border p-5",active?"border-[#59afe3] bg-[#e7f6ff] shadow-[0_18px_50px_rgba(41,139,199,.12)]":s.status==="blocked"?"border-[#ffc0b5] bg-[#fff1ee]":"border-black/5 bg-white")}>
{active&&<motion.div className="absolute inset-x-0 top-0 h-1 bg-[#2e89c8]" animate={{opacity:[.25,1,.25]}} transition={{repeat:Infinity,duration:.8}}/>}<div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-white shadow-sm"><info.Icon className="size-4 text-[#1875af]"/></span><span className="rounded-full bg-white/80 px-2.5 py-1 text-[10px] font-medium capitalize">{s.status}</span></div><h3 className="mt-6 text-lg font-semibold">{info.title}</h3><p className="mt-2 min-h-16 text-xs leading-5 text-[#718095]">{info.copy}</p><div className="mt-5 border-t border-black/5 pt-4"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#8a98a8]">Now</p><p className="mt-2 text-sm font-medium leading-5">{s.task}</p><p className="mt-2 text-[11px] leading-5 text-[#68798b]">{s.lastDecision}</p></div>{active&&<div className="mt-4 flex gap-1">{[0,1,2].map(i=><motion.span key={i} className="size-1.5 rounded-full bg-[#2e89c8]" animate={{y:[0,-3,0],opacity:[.3,1,.3]}} transition={{repeat:Infinity,duration:.7,delay:i*.12}}/>)}</div>}</motion.article>})}</div></section>; }

function Proof({ snapshot }: { snapshot: KitchenSnapshot }) { const [open,setOpen]=useState(true); return <section className="rounded-[28px] bg-[#0d1c2b] text-white"><button className="flex w-full items-center justify-between p-5 text-left" onClick={()=>setOpen(!open)}><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-[#83d5ff]">Mozaik technical proof</p><h2 className="mt-2 text-xl font-semibold">Real runtime loops, event fan-out and overlap</h2></div>{open?<ChevronUp/>:<ChevronDown/>}</button>{open&&<div className="border-t border-white/10 p-5"><div className="grid gap-3 sm:grid-cols-3">{[["Inference","Live model only"],["Model",snapshot.model],["Peak overlap",`${snapshot.overlapPeak} loops`]].map(([a,b])=><div key={a} className="rounded-2xl bg-white/[.06] p-4"><p className="text-[9px] text-white/45">{a}</p><p className="mt-1 text-sm">{b}</p></div>)}</div><div className="mt-4 space-y-2">{snapshot.loops.slice(-20).map(l=><div key={l.loopId} className="grid gap-1 rounded-xl border border-white/10 p-3 text-[10px] sm:grid-cols-[110px_1fr_auto]"><span>{l.agentName}</span><span className="truncate font-mono text-white/45">{l.loopId}</span><span className="text-[#8dd9ff]">{l.finishedAt?`${l.finishedAt-l.startedAt}ms`:"LIVE"}</span></div>)}</div></div>}</section>; }

export function KitchenConsole(){ const [setup,setSetup]=useState(true); const [selected,setSelected]=useState<MenuItem[]>(["burger","fries","plantain","jollof-rice"]); const [scenario,setScenario]=useState<ScenarioId>("full"); const [snapshot,setSnapshot]=useState<KitchenSnapshot|null>(null); const [running,setRunning]=useState(false); const [error,setError]=useState<string|null>(null); const abort=useRef<AbortController|null>(null);
const toggle=(id:MenuItem)=>setSelected(x=>x.includes(id)?(x.length===1?x:x.filter(v=>v!==id)):(x.length>=10?x:[...x,id]));
const start=useCallback(async()=>{abort.current?.abort();const c=new AbortController();abort.current=c;setSetup(false);setRunning(true);setError(null);setSnapshot(null);try{const r=await fetch("/api/kitchen/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenario,menu:selected}),signal:c.signal});const body=await (r.ok?Promise.resolve(null):r.json().catch(()=>null));if(!r.ok||!r.body)throw new Error(body?.error||"Live kitchen could not start.");const reader=r.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const frames=buffer.split("\n\n");buffer=frames.pop()??"";for(const frame of frames){const data=frame.split("\n").find(l=>l.startsWith("data: "))?.slice(6);if(!data)continue;const event=JSON.parse(data) as KitchenStreamEvent;if(event.kind==="error")throw new Error(event.message);if(event.snapshot)setSnapshot(event.snapshot);if(event.kind==="complete")setRunning(false);}}}catch(e){if(e instanceof DOMException&&e.name==="AbortError")return;setError(e instanceof Error?e.message:"Live service failed.");setRunning(false)}},[scenario,selected]);
const reset=()=>{abort.current?.abort();setSetup(true);setSnapshot(null);setRunning(false);setError(null)};
if(setup)return <Shell><section className="bg-[#68b7e8]"><div className="mx-auto max-w-[1280px] px-5 py-14 sm:px-8 lg:py-20"><span className="inline-flex items-center gap-2 rounded-full bg-white/80 px-4 py-2 text-xs font-medium"><Sparkles className="size-3.5"/>Build a real service</span><h1 className="mt-6 max-w-4xl text-[clamp(3.2rem,8vw,7rem)] font-semibold leading-[.88] tracking-[-.075em]">Pick the food.<br/>Watch the kitchen think.</h1><p className="mt-6 max-w-2xl text-lg leading-7 text-[#17334b]/75">Choose up to 10 dishes from a 15-item restaurant menu. Dinner Rush sends the order to live Mozaik agents. There is no scripted fallback.</p></div></section><section className="mx-auto max-w-[1280px] px-5 py-10 sm:px-8"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold">1. Build the table order</p><p className="mt-1 text-xs text-[#718095]">{selected.length}/10 selected</p></div></div><div className="mt-4 grid gap-2 grid-cols-2 md:grid-cols-3 lg:grid-cols-5">{foods.map(f=>{const on=selected.includes(f.id);return <button key={f.id} onClick={()=>toggle(f.id)} className={cn("min-h-32 rounded-[20px] border p-4 text-left transition",on?"border-[#55aee3] bg-[#e9f7ff] shadow-sm":"border-black/5 bg-white hover:border-[#b7def5]")}><div className="flex justify-between"><span className="grid size-8 place-items-center rounded-xl bg-white"><ChefHat className="size-3.5 text-[#1875af]"/></span>{on&&<span className="grid size-6 place-items-center rounded-full bg-[#0d1c2b] text-white"><Check className="size-3"/></span>}</div><p className="mt-5 text-sm font-semibold">{f.name}</p><p className="mt-1 text-[10px] text-[#2e89c8]">{f.station}</p></button>})}</div><div className="mt-10"><p className="text-xs font-semibold">2. Choose what happens during service</p><div className="mt-4 grid gap-2 md:grid-cols-4">{scenarios.map(s=><button key={s.id} onClick={()=>setScenario(s.id)} className={cn("rounded-[20px] border p-4 text-left",scenario===s.id?"border-[#0d1c2b] bg-[#0d1c2b] text-white":"border-black/5 bg-white")}><p className="text-sm font-semibold">{s.title}</p><p className={cn("mt-2 text-[11px] leading-5",scenario===s.id?"text-white/55":"text-[#718095]")}>{s.copy}</p></button>)}</div></div><Button size="lg" onClick={()=>void start()} className="mt-8 h-14 rounded-full bg-[#b9f65e] px-7 text-[#102030] hover:bg-[#adf047]"><Play/>Start live dinner service<ArrowRight/></Button><div className="mt-14 grid gap-3 md:grid-cols-5">{(Object.keys(stationInfo) as StationId[]).map(id=>{const x=stationInfo[id];return <article key={id} className="rounded-[22px] border border-black/5 bg-white p-5"><x.Icon className="size-4 text-[#2e89c8]"/><h2 className="mt-5 font-semibold">{x.title}</h2><p className="mt-2 text-xs leading-5 text-[#718095]">{x.copy}</p></article>})}</div></section></Shell>;
return <Shell><section className="border-b border-black/5 bg-[#68b7e8]"><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-4 px-5 py-6 sm:px-8"><div className="flex items-center gap-3"><button onClick={reset} className="grid size-10 place-items-center rounded-full bg-white/80"><ArrowLeft className="size-4"/></button><div><p className="text-xs text-[#31536c]">Live dinner service</p><h1 className="text-2xl font-semibold">The kitchen is thinking.</h1></div></div><span className="rounded-full bg-[#0d1c2b] px-3 py-2 text-xs text-white">{running?"LIVE":"FINISHED"}</span></div></section><div className="mx-auto max-w-[1440px] space-y-5 px-5 py-6 sm:px-8">{error&&<div className="rounded-2xl border border-[#ffc2b8] bg-[#fff2ef] p-4 text-sm text-[#9b4536]"><strong>Live run stopped.</strong> {error}<button className="ml-3 underline" onClick={()=>void start()}>Retry</button></div>}{!snapshot?<div className="grid min-h-[520px] place-items-center rounded-[30px] bg-white"><div className="text-center"><RefreshCw className="mx-auto size-7 animate-spin text-[#2e89c8]"/><h2 className="mt-5 text-xl font-semibold">Creating five live agents</h2><p className="mt-2 text-sm text-[#718095]">Waiting for the first Mozaik runtime event.</p></div></div>:<><Decisions snapshot={snapshot}/><Workers snapshot={snapshot}/><Proof snapshot={snapshot}/>{snapshot.status==="complete"&&<section className="rounded-[28px] bg-[#dff3ff] p-6"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-[#247eba]">Final result</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{snapshot.safetyGate.passed?"Table served safely.":"Expo held the table safely."}</h2><p className="mt-3 max-w-2xl text-sm text-[#536a7d]">{snapshot.safetyGate.reason}</p><div className="mt-5 flex gap-2"><Button onClick={reset} className="rounded-full bg-[#0d1c2b]"><RefreshCw/>New service</Button><Button variant="outline" className="rounded-full bg-white" onClick={()=>{const text=[`Dinner Rush ${snapshot.runId}`,snapshot.safetyGate.reason,...snapshot.activities.slice().reverse().map(a=>`${a.actor}: ${a.message}`)].join("\n");const url=URL.createObjectURL(new Blob([text],{type:"text/plain"}));const a=document.createElement("a");a.href=url;a.download=`dinner-rush-${snapshot.runId}.txt`;a.click();URL.revokeObjectURL(url)}}><Download/>Export run</Button></div></section>}</>}</div></Shell>}
