"use client";

import Link from "next/link";
import { ArrowLeft, Check, ChefHat, ChevronDown, ChevronUp, CircleAlert, Download, Flame, PackageOpen, Play, RefreshCw, ShieldCheck, Soup, Sparkles, Zap } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useCallback, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { KitchenSnapshot, KitchenStreamEvent, ScenarioId, StationId } from "@/lib/kitchen/types";

type MenuItem = "burger" | "fries" | "salad";
const menuItems: { id: MenuItem; name: string; description: string; station: string }[] = [
  { id: "burger", name: "Smash Burger", description: "Toasted bun and grilled patties", station: "Prep + Grill" },
  { id: "fries", name: "House Fries", description: "Hot-line potato side", station: "Fryer" },
  { id: "salad", name: "Chopped Salad", description: "Fresh cold-side salad", station: "Pantry" },
];
const scenarios: { id: ScenarioId; title: string; description: string }[] = [
  { id: "rush", title: "Normal dinner rush", description: "A clean service with no surprise failure." },
  { id: "fryer", title: "Fryer breaks", description: "Equipment fails while the kitchen is already working." },
  { id: "allergy", title: "Late allergy note", description: "Safety information arrives after cooking starts." },
  { id: "full", title: "Everything goes wrong", description: "Fryer failure and a late allergy hit the same service." },
];
const stationIcons = { prep: ChefHat, grill: Flame, fryer: Soup, pantry: PackageOpen, expo: ShieldCheck } satisfies Record<StationId, typeof ChefHat>;

function statusCopy(status: string) { if (status === "thinking") return "Thinking live"; if (status === "working") return "Acting"; if (status === "blocked") return "Holding"; if (status === "ready") return "Decision applied"; return "Waiting"; }

function KitchenFloor({ snapshot }: { snapshot: KitchenSnapshot }) {
  return <section className="rounded-[22px] border border-border bg-card p-4 sm:p-5">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-semibold">Live kitchen</h2><p className="mt-1 text-xs text-muted-foreground">These cards update from backend Mozaik runtime events.</p></div><div className="flex gap-2"><span className="rounded-full border border-primary/25 bg-primary/[0.08] px-3 py-1 text-[10px] text-primary">{snapshot.loops.filter((loop) => !loop.finishedAt).length} thinking now</span><span className="rounded-full border border-border px-3 py-1 text-[10px] text-muted-foreground">peak {snapshot.overlapPeak} together</span></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{snapshot.stations.map((station) => { const Icon = stationIcons[station.id]; const active = station.status === "thinking" || station.status === "working"; return <motion.article key={station.id} layout className={cn("relative min-h-52 overflow-hidden rounded-[16px] border bg-[#12100e] p-4", active ? "border-primary/60 shadow-[0_0_30px_rgba(234,179,8,0.08)]" : station.status === "blocked" ? "border-destructive/45" : "border-border")}>
      {active ? <motion.div className="absolute inset-x-0 top-0 h-0.5 bg-primary" animate={{ opacity: [0.2, 1, 0.2] }} transition={{ repeat: Infinity, duration: 0.8 }} /> : null}
      <div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-[10px] bg-white/[0.05]"><Icon className="size-4" /></span><span className={cn("rounded-full px-2 py-1 text-[9px]", active ? "bg-primary/10 text-primary" : station.status === "blocked" ? "bg-destructive/10 text-destructive" : "bg-white/[0.05] text-muted-foreground")}>{statusCopy(station.status)}</span></div>
      <p className="mt-5 text-xs font-semibold">{station.name}</p><p className="mt-2 min-h-12 text-sm leading-5">{station.task}</p>
      {active ? <div className="mt-3 flex gap-1">{[0,1,2].map((i) => <motion.span key={i} className="size-1.5 rounded-full bg-primary" animate={{ opacity: [0.2,1,0.2], y: [0,-3,0] }} transition={{ repeat: Infinity, duration: 0.8, delay: i * 0.12 }} />)}</div> : null}
      <p className="mt-4 border-t border-border/60 pt-3 text-[10px] leading-4 text-muted-foreground">{station.lastDecision}</p>
    </motion.article>; })}</div>
  </section>;
}

function Activity({ snapshot }: { snapshot: KitchenSnapshot }) { return <section className="rounded-[20px] border border-border bg-card"><div className="border-b border-border p-4"><h2 className="text-sm font-semibold">Live decision feed</h2><p className="mt-1 text-xs text-muted-foreground">New backend events appear here as the agents react.</p></div><div className="max-h-[520px] overflow-y-auto p-2"><AnimatePresence initial={false}>{snapshot.activities.slice(0,18).map((a) => <motion.div key={a.id} initial={{ opacity:0, x:12 }} animate={{ opacity:1,x:0 }} className="border-b border-border/60 p-3 last:border-0"><div className="flex items-center gap-2"><span className={cn("size-1.5 rounded-full",a.tone === "danger" ? "bg-destructive" : "bg-primary")} /><span className="text-[10px] font-medium text-muted-foreground">{a.actor}</span></div><p className="mt-1.5 text-xs leading-5">{a.message}</p></motion.div>)}</AnimatePresence></div></section>; }

function TechnicalProof({ snapshot }: { snapshot: KitchenSnapshot }) { const [open,setOpen]=useState(false); return <section className="rounded-[20px] border border-border bg-card"><button onClick={()=>setOpen(!open)} className="flex w-full items-center justify-between p-4 text-left"><div><p className="text-sm font-semibold">Prove this was actually running</p><p className="mt-1 text-xs text-muted-foreground">Inspect real loop IDs, timing and execution mode.</p></div>{open?<ChevronUp className="size-4"/>:<ChevronDown className="size-4"/>}</button>{open?<div className="border-t border-border p-4"><div className="mb-4 grid gap-2 sm:grid-cols-3">{[["Execution",snapshot.mode === "openai-live" ? "Live model inference" : "Local demo inference"],["Model",snapshot.model],["Peak overlap",`${snapshot.overlapPeak} concurrent loops`]].map(([l,v])=><div key={l} className="rounded-xl bg-white/[0.03] p-3"><p className="text-[9px] text-muted-foreground">{l}</p><p className="mt-1 font-mono text-xs">{v}</p></div>)}</div><div className="space-y-2">{snapshot.loops.slice(-20).map((loop)=><div key={loop.loopId} className="grid gap-1 rounded-xl border border-border p-3 text-[10px] sm:grid-cols-[120px_1fr_auto]"><span>{loop.agentName}</span><span className="truncate font-mono text-muted-foreground">{loop.loopId}</span><span className="text-primary">{loop.finishedAt?`${loop.finishedAt-loop.startedAt}ms`:"LIVE"}</span></div>)}</div></div>:null}</section>; }

function Result({ snapshot,onAgain }:{snapshot:KitchenSnapshot;onAgain:()=>void}) { const served=snapshot.orders.filter(o=>o.status==="served").length; const held=snapshot.orders.filter(o=>o.status==="held").length; const report=["DINNER RUSH AGENT RUN",`Run: ${snapshot.runId}`,`Mode: ${snapshot.mode}`,`Model: ${snapshot.model}`,`Result: ${snapshot.safetyGate.reason}`,`Peak concurrent loops: ${snapshot.overlapPeak}`,"","DECISION LOG",...snapshot.activities.slice().reverse().map(a=>`${a.actor}: ${a.message}`)].join("\n"); const download=()=>{const blob=new Blob([report],{type:"text/plain"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`dinner-rush-${snapshot.runId}.txt`;a.click();URL.revokeObjectURL(url);}; return <motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="rounded-[22px] border border-primary/25 bg-primary/[0.05] p-6"><p className="text-xs font-medium text-primary">SERVICE COMPLETE</p><h2 className="mt-2 text-2xl font-semibold">{snapshot.safetyGate.passed?"The kitchen got the order out safely.":"The kitchen refused an unsafe release."}</h2><p className="mt-2 text-sm text-muted-foreground">{snapshot.safetyGate.reason}</p><div className="mt-5 grid gap-2 sm:grid-cols-4">{[["Served",served],["Held",held],["Peak AI overlap",`${snapshot.overlapPeak}×`],["Execution",snapshot.mode === "openai-live"?"Live AI":"Demo"]].map(([l,v])=><div key={l} className="rounded-xl border border-border bg-background/50 p-4"><p className="text-xl font-semibold">{v}</p><p className="mt-1 text-[10px] text-muted-foreground">{l}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={onAgain}><RefreshCw/>New service</Button><Button variant="outline" onClick={download}><Download/>Export agent run</Button></div></motion.section>; }

export function KitchenConsole(){
  const [step,setStep]=useState<"setup"|"service">("setup"); const [selectedMenu,setSelectedMenu]=useState<MenuItem[]>(["burger","fries","salad"]); const [scenario,setScenario]=useState<ScenarioId>("full"); const [snapshot,setSnapshot]=useState<KitchenSnapshot|null>(null); const [running,setRunning]=useState(false); const [error,setError]=useState<string|null>(null); const abortRef=useRef<AbortController|null>(null);
  const toggle=(id:MenuItem)=>setSelectedMenu(c=>c.includes(id)?(c.length===1?c:c.filter(x=>x!==id)):[...c,id]);
  const start=useCallback(async()=>{abortRef.current?.abort();const controller=new AbortController();abortRef.current=controller;setStep("service");setRunning(true);setError(null);setSnapshot(null);try{const response=await fetch("/api/kitchen/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenario,menu:selectedMenu}),signal:controller.signal});if(!response.ok||!response.body)throw new Error("The live kitchen backend did not start.");const reader=response.body.getReader();const decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const frames=buffer.split("\n\n");buffer=frames.pop()??"";for(const frame of frames){const data=frame.split("\n").find(l=>l.startsWith("data: "))?.slice(6);if(!data)continue;const event=JSON.parse(data) as KitchenStreamEvent;if(event.kind==="error")throw new Error(event.message);if(event.snapshot)setSnapshot(event.snapshot);if(event.kind==="complete")setRunning(false);}}}catch(e){if(e instanceof DOMException&&e.name==="AbortError")return;setError(e instanceof Error?e.message:"Dinner service stopped unexpectedly.");setRunning(false);}},[scenario,selectedMenu]);
  const active=useMemo(()=>snapshot?.loops.filter(l=>!l.finishedAt).length??0,[snapshot]);
  if(step==="setup")return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 text-sm font-bold tracking-[0.12em]"><Zap className="size-4 text-primary" fill="currentColor"/>DINNER RUSH</Link><span className="hidden text-xs text-muted-foreground sm:block">You create the rush. The agents run the kitchen.</span></div></header><div className="mx-auto max-w-5xl px-5 py-12"><div className="max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/[0.06] px-3 py-1.5 text-[10px] text-primary"><Sparkles className="size-3"/>BUILD A LIVE SERVICE</span><h1 className="mt-5 text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">Put the AI kitchen under pressure.</h1><p className="mt-4 text-base leading-7 text-muted-foreground">Choose the food and the crisis. When you start, real backend agent loops receive the same changing kitchen state and decide what to do.</p></div><section className="mt-10"><p className="mb-4 text-sm font-semibold">1. Pick the order</p><div className="grid gap-3 md:grid-cols-3">{menuItems.map(item=>{const selected=selectedMenu.includes(item.id);return <button key={item.id} onClick={()=>toggle(item.id)} className={cn("rounded-2xl border p-5 text-left transition",selected?"border-primary bg-primary/[0.06]":"border-border bg-card hover:border-white/20")}><div className="flex justify-between"><ChefHat className={cn("size-5",selected?"text-primary":"text-muted-foreground")}/>{selected?<span className="grid size-5 place-items-center rounded-full bg-primary text-primary-foreground"><Check className="size-3"/></span>:null}</div><h2 className="mt-8 font-semibold">{item.name}</h2><p className="mt-2 text-xs text-muted-foreground">{item.description}</p><p className="mt-4 text-[10px] text-primary">{item.station}</p></button>})}</div></section><section className="mt-9"><p className="mb-4 text-sm font-semibold">2. Choose what hits the kitchen</p><div className="grid gap-3 sm:grid-cols-2">{scenarios.map(s=><button key={s.id} onClick={()=>setScenario(s.id)} className={cn("rounded-2xl border p-4 text-left",scenario===s.id?"border-primary bg-primary/[0.06]":"border-border bg-card")}><p className="text-sm font-semibold">{s.title}</p><p className="mt-1 text-xs text-muted-foreground">{s.description}</p></button>)}</div></section><Button size="lg" className="mt-9" onClick={()=>void start()}><Play/>Start live dinner service</Button></div></main>;
  return <main className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-40 border-b border-border bg-background/90 backdrop-blur-xl"><div className="mx-auto flex min-h-16 max-w-[1500px] items-center justify-between gap-3 px-4"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" onClick={()=>{abortRef.current?.abort();setStep("setup");setSnapshot(null);setRunning(false)}}><ArrowLeft/></Button><div><p className="text-sm font-bold tracking-[0.12em]">DINNER RUSH</p><p className="text-[9px] text-muted-foreground">LIVE AGENT SERVICE</p></div></div><div className="flex items-center gap-2"><span className={cn("rounded-full border px-3 py-1 text-[10px]",running?"border-primary/30 bg-primary/10 text-primary":"border-border text-muted-foreground")}>{running?`${active} agents thinking now`:"service finished"}</span>{snapshot?<span className="hidden rounded-full border border-border px-3 py-1 text-[10px] sm:block">{snapshot.mode === "openai-live"?"LIVE MODEL":"DEMO MODE"}</span>:null}</div></div></header><div className="mx-auto max-w-[1500px] px-4 py-6">{error?<div className="mb-5 flex items-center gap-2 rounded-xl border border-destructive/40 p-4 text-sm"><CircleAlert className="size-4 text-destructive"/>{error}</div>:null}{!snapshot?<div className="grid min-h-[600px] place-items-center"><div className="text-center"><RefreshCw className="mx-auto size-6 animate-spin text-primary"/><h1 className="mt-5 text-xl font-semibold">Starting the backend kitchen...</h1><p className="mt-2 text-sm text-muted-foreground">Joining five Mozaik agents and firing your order into shared state.</p></div></div>:<div className="space-y-5"><div><p className="text-[10px] font-medium text-primary">RUN {snapshot.runId}</p><h1 className="mt-2 text-2xl font-semibold tracking-[-0.04em]">{running?"The kitchen is making decisions right now.":"Dinner service is complete."}</h1><p className="mt-2 text-sm text-muted-foreground">{snapshot.orders[0]?.label} · {snapshot.scenario.replaceAll("_"," ")}</p></div><KitchenFloor snapshot={snapshot}/><div className="grid gap-5 xl:grid-cols-[1fr_380px]"><TechnicalProof snapshot={snapshot}/><Activity snapshot={snapshot}/></div>{!running?<Result snapshot={snapshot} onAgain={()=>{setStep("setup");setSnapshot(null)}}/>:null}</div>}</div></main>;
}
